---
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: add a list of user
            user: name="{{items}}" state=present
            with items:
                  -suvo1
                   suvo2
                   suvo3