---
- hosts: demo
  become: yes
  vars:
    - username: arghya
    - home: /home/sammy
    - pkg: httpd
  tasks:
    - name: print variables
      debug:
              msg: "Username: {{ username }}, Home dir: {{ home }}"
    - name: install httpd
      yum: name="{{ pkg }}" state=present
    - name: start httpd
      service: name="{{ pkg }}" state=started

    