---
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
        - name: install_httpd
          yum: name=httpd state=present
          when: ansible_os_family == "RedHat"
        - name: install_apache2
          yum: name=apache2 state=present
          when: ansible_os_family == "Debian"

        